// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// User is the golang structure for table user.
type User struct {
	Uid      string `json:"uid"      ` //
	Nickname string `json:"nickname" ` //
	Password string `json:"password" ` //
	Credit   uint   `json:"credit"   ` //
}
