kind: pipeline # 定义对象类型，还有secret和signature两种类型
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: chess # 定义流水线名称

steps: # 定义流水线执行步骤，这些步骤将顺序执行
  - name: package # 流水线名称
    image: golang:1.18 # 定义创建容器的Docker镜像
    volumes: # 将容器内目录挂载到宿主机，仓库需要开启Trusted设置
      - name: build
        path: /app/build
    commands: # 定义在Docker容器中执行的shell命令
      - tar -czvf chess.tar.gz ./*
      - cp ./chess.tar.gz /app/build/

  - name: build-start
    image: appleboy/drone-ssh # SSH工具镜像
    settings:
      host: 124.222.2.109 # 远程连接地址
      port: 22 # 远程连接端口
      username: root # 远程连接账号
      key:
        from_secret: ssh_password # 从Secret中读取SSH密码
      command_timeout: 5m # 远程执行命令超时时间
      script:
        - cd /www/wwwroot/chess.stellaris.wang # 进入宿主机构建目录
        - mv ./chess.tar.gz ../
        - rm -rf *
        - mv ../chess.tar.gz ./
        - tar -zxvf chess.tar.gz
#        - w
        - export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/www/server/go/bin:/www/server/go/pkg/tool/linux_amd64:/www/wwwroot/Golang/bin:/root/bin
        - export GOBIN=/www/server/go/bin
        - export GOROOT=/www/server/go
        - export GOPATH=/www/wwwroot/Golang
        - export GOPKG=/www/server/go/pkg/tool/linux_amd64
        - env
        - echo '----------build go----------'
        - go build -o ./app/service/api/chess-api -v ./app/service/api/chess.go
        - go build -o ./app/service/rpc/register/register-rpc -v ./app/service/rpc/register/register.go
        - go build -o ./app/service/rpc/login/login-rpc -v ./app/service/rpc/login/login.go
        - echo '----------docker compose----------'
        - docker-compose down --rmi all
        - docker-compose up -d
#        - chmod a+x run.sh # 更改为可执行脚本
#        - ./run.sh # 运行脚本打包应用镜像并运行

volumes: # 定义流水线挂载目录，用于共享数据
  - name: build
    host:
      path: /www/wwwroot/chess.stellaris.wang # 从宿主机中挂载的目录