// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Uid      string `form:"uid"`
	Nickname string `form:"nickname"`
	Password string `form:"password"`
}

type RegisterRes struct {
	Ok  bool   `json:"success"`
	Msg string `json:"msg"`
}

type LoginReq struct {
	Uid      string `form:"uid"`
	Password string `form:"password"`
}

type LoginRes struct {
	Ok  bool   `json:"success"`
	Msg string `json:"msg"`
}
